In [1]:
import numpy as np

In [2]:
a = np.array([[6, 13, 11], [13, 35, 25], [11, 25, 23]])
invA = np.linalg.inv(a)
print(a)
print(invA)
b = np.array([10, 18, 19])
print(b)
answer = np.multiply(invA, b)
# answer = invA * b
# print(answer)
answer

[[ 6 13 11]
 [13 35 25]
 [11 25 23]]
[[ 1.66666667 -0.22222222 -0.55555556]
 [-0.22222222  0.15740741 -0.06481481]
 [-0.55555556 -0.06481481  0.37962963]]
[10 18 19]


array([[ 16.66666667,  -4.        , -10.55555556],
       [ -2.22222222,   2.83333333,  -1.23148148],
       [ -5.55555556,  -1.16666667,   7.21296296]])

In [3]:
a = np.array([[21, 105, 717.5], [105, 717.5, 5512.5], [717.5, 5512.5, 45166.6]])
a

array([[2.10000e+01, 1.05000e+02, 7.17500e+02],
       [1.05000e+02, 7.17500e+02, 5.51250e+03],
       [7.17500e+02, 5.51250e+03, 4.51666e+04]])

In [4]:
invA = np.linalg.inv(a)
invA

array([[ 0.35629907, -0.13890659,  0.01129326],
       [-0.13890659,  0.07652063, -0.00713258],
       [ 0.01129326, -0.00713258,  0.00071326]])

In [5]:
b = [930.4, 7012.9, 57136.8]
b

[930.4, 7012.9, 57136.8]

In [8]:
np.dot(invA, b)
# np.matmul(invA, b)
# invA @ b
# 上二つも同様に行列の積が求められるが、三次元以上の多次元配列での処理が異なる
# numpy.matrixなら
# invA * b
# でも行列の積が算出される。

array([ 2.62316218, -0.14009696,  1.24045125])

In [32]:
# 小テスト
list = np.array([[-2, 3, -30], [-1, 3, -10], [0, 0, 10], [1, 0, 0], [2, -1, 20]])

x1 = 0
for i in range(5):
    x1 = x1 + list[i][0]
x2 = 0
for i in range(5):
    x1 += list[i, 1]
t = 0
for i in range(5):
    t += list[i, 2]

    
x11 = 0
for i in range(5):
    x11 += list[i, 0] * list[i, 0]
x22 = 0
for i in range(5):
    x22 += list[i, 1] * list[i, 1]
x12 = 0
for i in range(5):
    x12 += list[i, 0] * list[i, 1]
x1t = 0
for i in range(5):
    x1t += list[i, 0] * list[i, 2]
x2t = 0
for i in range(5):
    x2t += list[i, 1] * list[i, 2]

a = np.array([[5, x1, x2], [x1, x11, x12], [x2, x12, x22]])

b = np.array([[t], [x1t], [x2t]])

invA = np.linalg.inv(a)

answer = np.dot(invA, b)
print(answer[2, 0])


-23.846153846153854
